fix(rebar3): compile failed on multiple-user host
emqx/rebar3 pull request #5
Opened 2021-06-16 07:49 UTC by terry-xiaoyu

2021-06-16 07:56 UTC, zmstone approved these changes

2021-06-16 07:56 UTC, zmstone requested changes
please update version

2021-06-16 07:58 UTC, zmstone commented
https://github.com/emqx/rebar3/blob/v3.14.3-emqx/rebar.config#L27

2021-06-24 02:21 UTC, terry-xiaoyu commented
> https://github.com/emqx/rebar3/blob/v3.14.3-emqx/rebar.config#L27

Updated

2021-06-24 03:35 UTC, zmstone approved these changes

2022-01-20 02:14 UTC, merged